export interface CpvEntry {
  code: string;
  label: string;
  category: string;
}

/** CPV (Common Procurement Vocabulary) codes relevant to García & Smith.
 *  Source: config/codigos_cpv.txt
 */
export const AGENCY_CPV_CODES: CpvEntry[] = [
  // Marketing & Comunicación
  { code: "79310000", label: "Servicios de estudios de mercado", category: "Marketing & Comunicación" },
  { code: "79311000", label: "Servicios de encuestas", category: "Marketing & Comunicación" },
  { code: "79311100", label: "Servicios de diseño de encuestas", category: "Marketing & Comunicación" },
  { code: "79311200", label: "Servicios de realización de encuestas", category: "Marketing & Comunicación" },
  { code: "79311210", label: "Servicios de encuesta telefónica", category: "Marketing & Comunicación" },
  { code: "79311300", label: "Servicios de investigación de mercado", category: "Marketing & Comunicación" },
  { code: "79311400", label: "Servicios de evaluación de publicidad", category: "Marketing & Comunicación" },
  { code: "79312000", label: "Servicios de análisis de mercado", category: "Marketing & Comunicación" },
  { code: "79315000", label: "Servicios de investigación social", category: "Marketing & Comunicación" },
  { code: "79320000", label: "Servicios de sondeo de opinión pública", category: "Marketing & Comunicación" },
  { code: "79330000", label: "Servicios estadísticos", category: "Marketing & Comunicación" },
  { code: "79340000", label: "Servicios de publicidad y marketing", category: "Marketing & Comunicación" },
  { code: "79341000", label: "Servicios de publicidad", category: "Marketing & Comunicación" },
  { code: "79341100", label: "Servicios de consultoría publicitaria", category: "Marketing & Comunicación" },
  { code: "79341200", label: "Servicios de gestión publicitaria", category: "Marketing & Comunicación" },
  { code: "79341400", label: "Servicios de campaña de publicidad televisiva", category: "Marketing & Comunicación" },
  { code: "79342000", label: "Servicios de marketing", category: "Marketing & Comunicación" },
  { code: "79342100", label: "Servicios de marketing directo", category: "Marketing & Comunicación" },
  { code: "79342200", label: "Servicios de promoción", category: "Marketing & Comunicación" },
  { code: "79342300", label: "Servicios de atención al cliente", category: "Marketing & Comunicación" },
  { code: "79342320", label: "Servicios de atención y cuidado al cliente", category: "Marketing & Comunicación" },
  { code: "79342400", label: "Servicios de relaciones con clientes", category: "Marketing & Comunicación" },
  { code: "79350000", label: "Servicios de suministro de personal de publicidad y marketing", category: "Marketing & Comunicación" },
  { code: "79360000", label: "Servicios de distribución de material publicitario", category: "Marketing & Comunicación" },
  { code: "79416000", label: "Servicios de relaciones públicas", category: "Marketing & Comunicación" },
  { code: "79416100", label: "Servicios de gestión de relaciones públicas", category: "Marketing & Comunicación" },
  { code: "79416200", label: "Consultoría en relaciones públicas", category: "Marketing & Comunicación" },

  // Consultoría & Gestión
  { code: "79400000", label: "Servicios de consultoría empresarial y de gestión", category: "Consultoría & Gestión" },
  { code: "79410000", label: "Servicios de consultoría empresarial y de gestión", category: "Consultoría & Gestión" },
  { code: "79411000", label: "Servicios de consultoría en gestión general", category: "Consultoría & Gestión" },
  { code: "79411100", label: "Servicios de consultoría en desarrollo empresarial", category: "Consultoría & Gestión" },
  { code: "79412000", label: "Servicios de consultoría en gestión financiera", category: "Consultoría & Gestión" },
  { code: "79413000", label: "Servicios de consultoría en gestión de marketing", category: "Consultoría & Gestión" },
  { code: "79414000", label: "Servicios de consultoría en gestión de recursos humanos", category: "Consultoría & Gestión" },
  { code: "79415000", label: "Servicios de consultoría en gestión de producción", category: "Consultoría & Gestión" },
  { code: "79415200", label: "Servicios de consultoría en diseño", category: "Consultoría & Gestión" },
  { code: "79418000", label: "Servicios de consultoría en adquisiciones", category: "Consultoría & Gestión" },
  { code: "79419000", label: "Servicios de consultoría en evaluación", category: "Consultoría & Gestión" },
  { code: "79420000", label: "Servicios relacionados con la gestión", category: "Consultoría & Gestión" },
  { code: "79421000", label: "Servicios de gestión de proyectos", category: "Consultoría & Gestión" },
  { code: "79421100", label: "Supervisión de proyectos", category: "Consultoría & Gestión" },
  { code: "79421200", label: "Diseño de proyectos", category: "Consultoría & Gestión" },
  { code: "79430000", label: "Servicios de gestión de crisis", category: "Consultoría & Gestión" },
  { code: "79998000", label: "Servicios de coaching", category: "Consultoría & Gestión" },

  // Digital & Tecnología
  { code: "72200000", label: "Servicios de programación y consultoría informática", category: "Digital & Tecnología" },
  { code: "72210000", label: "Servicios de programación de productos de software empaquetado", category: "Digital & Tecnología" },
  { code: "72212000", label: "Servicios de programación de software de aplicación", category: "Digital & Tecnología" },
  { code: "72212224", label: "Servicios de desarrollo de software de páginas web", category: "Digital & Tecnología" },
  { code: "72220000", label: "Servicios de consultoría en sistemas e informática", category: "Digital & Tecnología" },
  { code: "72230000", label: "Servicios de desarrollo de software personalizado", category: "Digital & Tecnología" },
  { code: "72240000", label: "Servicios de análisis y programación de sistemas", category: "Digital & Tecnología" },
  { code: "72300000", label: "Servicios de datos", category: "Digital & Tecnología" },
  { code: "72310000", label: "Servicios de tratamiento de datos", category: "Digital & Tecnología" },
  { code: "72312000", label: "Servicios de introducción de datos", category: "Digital & Tecnología" },
  { code: "72313000", label: "Servicios de captura de datos", category: "Digital & Tecnología" },
  { code: "72314000", label: "Servicios de recopilación y compilación de datos", category: "Digital & Tecnología" },
  { code: "72315000", label: "Servicios de gestión y soporte de redes de datos", category: "Digital & Tecnología" },
  { code: "72316000", label: "Servicios de análisis de datos", category: "Digital & Tecnología" },
  { code: "72317000", label: "Servicios de almacenamiento de datos", category: "Digital & Tecnología" },
  { code: "72318000", label: "Servicios de transmisión de datos", category: "Digital & Tecnología" },
  { code: "72319000", label: "Servicios de suministro de datos", category: "Digital & Tecnología" },
  { code: "72320000", label: "Servicios de bases de datos", category: "Digital & Tecnología" },
  { code: "72321000", label: "Servicios de bases de datos de valor añadido", category: "Digital & Tecnología" },
  { code: "72322000", label: "Servicios de gestión electrónica de datos", category: "Digital & Tecnología" },
  { code: "72400000", label: "Servicios de Internet", category: "Digital & Tecnología" },
  { code: "72410000", label: "Servicios de proveedor", category: "Digital & Tecnología" },
  { code: "72411000", label: "Proveedores de servicios de Internet (ISP)", category: "Digital & Tecnología" },
  { code: "72412000", label: "Proveedores de servicios de correo electrónico", category: "Digital & Tecnología" },
  { code: "72413000", label: "Servicios de diseño de sitios web", category: "Digital & Tecnología" },
  { code: "72414000", label: "Proveedores de software de motor de búsqueda web", category: "Digital & Tecnología" },
  { code: "72415000", label: "Servicios de mantenimiento de software para Internet o Intranet", category: "Digital & Tecnología" },
  { code: "72416000", label: "Proveedores de servicios de aplicaciones", category: "Digital & Tecnología" },
  { code: "72417000", label: "Nombres de dominio de Internet", category: "Digital & Tecnología" },
  { code: "72420000", label: "Servicios de desarrollo de Internet", category: "Digital & Tecnología" },
  { code: "72421000", label: "Servicios de desarrollo de aplicaciones cliente para Internet o intranet", category: "Digital & Tecnología" },
  { code: "72422000", label: "Servicios de desarrollo de aplicaciones servidor para Internet o intranet", category: "Digital & Tecnología" },
  { code: "72500000", label: "Servicios informáticos", category: "Digital & Tecnología" },
  { code: "72510000", label: "Servicios de gestión informática", category: "Digital & Tecnología" },
  { code: "72511000", label: "Servicios de software de gestión de redes", category: "Digital & Tecnología" },
  { code: "72512000", label: "Servicios de gestión de documentos", category: "Digital & Tecnología" },
  { code: "72514000", label: "Servicios de gestión de instalaciones informáticas", category: "Digital & Tecnología" },
  { code: "72520000", label: "Servicios de apoyo y consultoría informática", category: "Digital & Tecnología" },
  { code: "72521000", label: "Servicios de soporte técnico informático", category: "Digital & Tecnología" },
  { code: "72540000", label: "Servicios de actualización de ordenadores", category: "Digital & Tecnología" },
  { code: "72590000", label: "Servicios informáticos profesionales", category: "Digital & Tecnología" },

  // Diseño & Producción Gráfica
  { code: "22100000", label: "Libros impresos, folletos y hojas sueltas", category: "Diseño & Producción" },
  { code: "22110000", label: "Libros impresos", category: "Diseño & Producción" },
  { code: "22140000", label: "Hojas sueltas", category: "Diseño & Producción" },
  { code: "22150000", label: "Folletos", category: "Diseño & Producción" },
  { code: "22160000", label: "Cuadernillos", category: "Diseño & Producción" },
  { code: "22200000", label: "Diarios, revistas profesionales y publicaciones periódicas", category: "Diseño & Producción" },
  { code: "22314000", label: "Dibujos", category: "Diseño & Producción" },
  { code: "22460000", label: "Material publicitario, catálogos de ventas y guías", category: "Diseño & Producción" },
  { code: "22461000", label: "Catálogos", category: "Diseño & Producción" },
  { code: "22462000", label: "Material publicitario", category: "Diseño & Producción" },
  { code: "22463000", label: "Folletos de promoción de ventas", category: "Diseño & Producción" },
  { code: "22470000", label: "Manuales", category: "Diseño & Producción" },
  { code: "22900000", label: "Impresos varios", category: "Diseño & Producción" },
  { code: "79800000", label: "Servicios de impresión y servicios conexos", category: "Diseño & Producción" },
  { code: "79810000", label: "Servicios de impresión", category: "Diseño & Producción" },
  { code: "79811000", label: "Servicios de impresión digital", category: "Diseño & Producción" },
  { code: "79812000", label: "Servicios de composición tipográfica", category: "Diseño & Producción" },
  { code: "79820000", label: "Servicios relacionados con la impresión", category: "Diseño & Producción" },
  { code: "79821000", label: "Servicios de acabado de impresión", category: "Diseño & Producción" },
  { code: "79821100", label: "Servicios de corrección de pruebas", category: "Diseño & Producción" },
  { code: "79822000", label: "Servicios de composición", category: "Diseño & Producción" },
  { code: "79822100", label: "Servicios de composición tipográfica", category: "Diseño & Producción" },
  { code: "79822200", label: "Servicios de grabado", category: "Diseño & Producción" },
  { code: "79822300", label: "Servicios de serigrafía", category: "Diseño & Producción" },
  { code: "79822400", label: "Servicios de litografía", category: "Diseño & Producción" },
  { code: "79822500", label: "Servicios de diseño gráfico", category: "Diseño & Producción" },
  { code: "79823000", label: "Servicios de impresión y entrega", category: "Diseño & Producción" },
  { code: "79824000", label: "Servicios de impresión y distribución", category: "Diseño & Producción" },
  { code: "79930000", label: "Servicios especializados de diseño", category: "Diseño & Producción" },
  { code: "79931000", label: "Servicios de decoración de interiores", category: "Diseño & Producción" },
  { code: "79932000", label: "Servicios de diseño de interiores", category: "Diseño & Producción" },
  { code: "79933000", label: "Servicios de apoyo al diseño", category: "Diseño & Producción" },

  // Fotografía
  { code: "79960000", label: "Fotografía y servicios conexos", category: "Fotografía" },
  { code: "79961000", label: "Servicios de fotografía", category: "Fotografía" },
  { code: "79961100", label: "Servicios de fotografía publicitaria", category: "Fotografía" },
  { code: "79961200", label: "Servicios de fotografía aérea", category: "Fotografía" },
  { code: "79961300", label: "Servicios de microfilm", category: "Fotografía" },
  { code: "79962000", label: "Servicios de revelado fotográfico", category: "Fotografía" },
  { code: "79963000", label: "Servicios de restauración, copiado y retoque fotográfico", category: "Fotografía" },

  // Audiovisual & Producción de Contenido
  { code: "92100000", label: "Servicios de cine y vídeo", category: "Audiovisual & Producción" },
  { code: "92110000", label: "Producción de películas y servicios conexos", category: "Audiovisual & Producción" },
  { code: "92111000", label: "Servicios de producción de películas publicitarias o de promoción y vídeo", category: "Audiovisual & Producción" },
  { code: "92111100", label: "Servicios de producción de cine para películas o vídeos de promoción", category: "Audiovisual & Producción" },
  { code: "92111200", label: "Servicios de producción de vídeo para películas publicitarias", category: "Audiovisual & Producción" },
  { code: "92111210", label: "Servicios de producción de vídeo para películas promocionales", category: "Audiovisual & Producción" },
  { code: "92111220", label: "Servicios de producción de vídeo para películas publicitarias", category: "Audiovisual & Producción" },
  { code: "92111300", label: "Servicios de reproducción de películas publicitarias o de promoción", category: "Audiovisual & Producción" },
  { code: "92112000", label: "Servicios de distribución de películas publicitarias o de promoción", category: "Audiovisual & Producción" },
  { code: "92120000", label: "Servicios de distribución de películas y servicios conexos", category: "Audiovisual & Producción" },
  { code: "92130000", label: "Servicios de proyección cinematográfica", category: "Audiovisual & Producción" },
  { code: "92140000", label: "Servicios de locutores", category: "Audiovisual & Producción" },
  { code: "92200000", label: "Servicios de radio y televisión", category: "Audiovisual & Producción" },
  { code: "92210000", label: "Servicios de radio", category: "Audiovisual & Producción" },
  { code: "92211000", label: "Servicios de producción de programas de radio", category: "Audiovisual & Producción" },
  { code: "92220000", label: "Servicios de televisión", category: "Audiovisual & Producción" },
  { code: "92221000", label: "Servicios de producción de programas de televisión", category: "Audiovisual & Producción" },
  { code: "92230000", label: "Servicios de radio y televisión por cable", category: "Audiovisual & Producción" },
  { code: "92312000", label: "Servicios de artes escénicas", category: "Audiovisual & Producción" },
  { code: "92312100", label: "Servicios de compañías de teatro", category: "Audiovisual & Producción" },
  { code: "92312200", label: "Servicios de orquestas, bandas y grupos musicales", category: "Audiovisual & Producción" },
  { code: "92313000", label: "Servicios de producciones artísticas", category: "Audiovisual & Producción" },
  { code: "92314000", label: "Servicios de artistas individuales", category: "Audiovisual & Producción" },
  { code: "92315000", label: "Servicios de artistas de variedades", category: "Audiovisual & Producción" },
  { code: "92316000", label: "Servicios de espectáculos de luz y sonido", category: "Audiovisual & Producción" },

  // Eventos & Comunicación Institucional
  { code: "79950000", label: "Servicios de organización de exposiciones, ferias y congresos", category: "Eventos" },
  { code: "79951000", label: "Servicios de organización de seminarios", category: "Eventos" },
  { code: "79952000", label: "Servicios de eventos", category: "Eventos" },
  { code: "79952100", label: "Servicios de organización de eventos culturales", category: "Eventos" },
  { code: "79953000", label: "Servicios de organización de festivales", category: "Eventos" },
  { code: "79954000", label: "Servicios de organización de fiestas", category: "Eventos" },
  { code: "79955000", label: "Servicios de organización de desfiles de moda", category: "Eventos" },
  { code: "79956000", label: "Servicios de organización de ferias y exposiciones", category: "Eventos" },
  { code: "79957000", label: "Servicios de organización de subastas", category: "Eventos" },

  // Formación & Comunicación Interna
  { code: "80000000", label: "Servicios de educación y formación", category: "Formación" },
  { code: "80400000", label: "Servicios de educación de adultos y otros servicios de educación", category: "Formación" },
  { code: "80410000", label: "Servicios de escuelas de formación variada", category: "Formación" },
  { code: "80500000", label: "Servicios de formación", category: "Formación" },
  { code: "80510000", label: "Servicios de formación especializada", category: "Formación" },
  { code: "80511000", label: "Servicios de formación de personal", category: "Formación" },
  { code: "80521000", label: "Servicios de programas de formación", category: "Formación" },
  { code: "80522000", label: "Seminarios de formación", category: "Formación" },
  { code: "80530000", label: "Servicios de formación profesional", category: "Formación" },
  { code: "80550000", label: "Servicios de formación en seguridad", category: "Formación" },

  // Relaciones con Medios & Comunicación
  { code: "92400000", label: "Servicios de agencias de noticias", category: "Medios & Comunicación" },
  { code: "92500000", label: "Servicios de biblioteca, archivo, museo y otros servicios culturales", category: "Medios & Comunicación" },
  { code: "92510000", label: "Servicios de biblioteca y archivo", category: "Medios & Comunicación" },
];

/** Return the human-readable label for a CPV code, or the code itself if not found. */
export function cpvLabel(code: string): string {
  const entry = AGENCY_CPV_CODES.find(
    (c) => c.code === code || code.startsWith(c.code.slice(0, 5))
  );
  return entry ? `${entry.code} — ${entry.label}` : code;
}

/** Check whether a CPV code matches any of the agency's CPV codes (prefix match). */
export function matchesCpv(code: string, cpvList: string[]): boolean {
  return cpvList.some((c) => code.startsWith(c));
}
